trigger:
- main
- feature/*

pool:
  name: Prod_infra

# =========================
# PARAMETERS (always on top)
# =========================
parameters:
- name: environment
  type: string
  default: dev
  values:
    - dev
    - prod

# =========================
# VARIABLES
# =========================
variables:
- name: workDir
  value: $(System.DefaultWorkingDirectory)/Env/${{ parameters.environment }}

# =========================
# STAGES
# =========================
stages:

# ---------- BUILD STAGE ----------
- stage: Build
  displayName: Build
  jobs:

  - job: TerraformInitFmtValidate
    displayName: Terraform Init, Fmt & Validate
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(workDir)
        backendServiceArm: miro-app
        backendAzureRmStorageAccountName: lovedevstorage01
        backendAzureRmContainerName: tfstates
        backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: $(workDir)

    - task: CmdLine@2
      displayName: Terraform Fmt Check
      inputs:
        script: terraform fmt -check -recursive

  - job: TerraformPlan
    displayName: Terraform Plan
    dependsOn: TerraformInitFmtValidate
    steps:
    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: miro-app

# ---------- SCANNING STAGE ----------
- stage: Scanning
  displayName: Security Scanning
  jobs:

  - job: TFSecScanning
    displayName: TFSEC Scan
    steps:
    - task: tfsec@1
      inputs:
        version: v1.26.0
        dir: $(workDir)

  - job: TfLintScanning
    displayName: TFLint Scan
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          tflint --init
          tflint $(workDir)

# ---------- DEPLOY STAGE ----------
- stage: Deploy
  displayName: Deploy
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:

  - job: ManualValidation
    displayName: Manual Approval
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: loveneesh@erloveneesh15891gmail.onmicrosoft.com
        approvers: loveneesh@erloveneesh15891gmail.onmicrosoft.com
        instructions: Please verify Terraform plan before apply

  - job: TerraformApply
    displayName: Terraform Apply
    dependsOn: ManualValidation
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(workDir)
        backendServiceArm: miro-app
        backendAzureRmStorageAccountName: lovedevstorage01
        backendAzureRmContainerName: tfstates
        backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: apply
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: miro-app
